"""init

Revision ID: 8412f198d5e5
Revises: a3d01adaeb28
Create Date: 2024-04-23 20:49:02.814235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8412f198d5e5'
down_revision: Union[str, None] = 'a3d01adaeb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rtsp_links')
    op.add_column('training_configurations', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_training_configurations_created_by'), 'training_configurations', ['created_by'], unique=False)
    op.create_foreign_key(None, 'training_configurations', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_configurations', type_='foreignkey')
    op.drop_index(op.f('ix_training_configurations_created_by'), table_name='training_configurations')
    op.drop_column('training_configurations', 'created_by')
    op.create_table('rtsp_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rtsp_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='rtsp_links_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='rtsp_links_pkey')
    )
    # ### end Alembic commands ###
